// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-colors/Option1Orange.tsx": () => import("../components/mockups/home-colors/Option1Orange.tsx"),
  "./components/mockups/home-colors/Option2BlueGradient.tsx": () => import("../components/mockups/home-colors/Option2BlueGradient.tsx"),
  "./components/mockups/home-colors/Option3Cyan.tsx": () => import("../components/mockups/home-colors/Option3Cyan.tsx"),
  "./components/mockups/home-colors/OptionPlaytomic.tsx": () => import("../components/mockups/home-colors/OptionPlaytomic.tsx")
};
